apiVersion: skaffold/v4beta13
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: salmantyagi/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: salmantyagi/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: salmantyagi/client-next
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .

    - image: salmantyagi/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: salmantyagi/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    - image: salmantyagi/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .